version: '3.8'

services:
  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    container_name: torua-coordinator
    ports:
      - "8080:8080"
    environment:
      - COORDINATOR_ADDR=:8080
      - HEALTH_CHECK_INTERVAL=5s
    networks:
      - torua-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  node1:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: torua-node1
    ports:
      - "8081:8081"
    environment:
      - NODE_ID=n1
      - NODE_LISTEN=:8081
      - NODE_ADDR=http://node1:8081
      - COORDINATOR_ADDR=http://coordinator:8080
    depends_on:
      coordinator:
        condition: service_healthy
    networks:
      - torua-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  node2:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: torua-node2
    ports:
      - "8082:8082"
    environment:
      - NODE_ID=n2
      - NODE_LISTEN=:8082
      - NODE_ADDR=http://node2:8082
      - COORDINATOR_ADDR=http://coordinator:8080
    depends_on:
      coordinator:
        condition: service_healthy
    networks:
      - torua-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  node3:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: torua-node3
    ports:
      - "8083:8083"
    environment:
      - NODE_ID=n3
      - NODE_LISTEN=:8083
      - NODE_ADDR=http://node3:8083
      - COORDINATOR_ADDR=http://coordinator:8080
    depends_on:
      coordinator:
        condition: service_healthy
    networks:
      - torua-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    profiles:
      - scale

networks:
  torua-network:
    driver: bridge
